### ISSUE TITLE
About the style and naming of supports with rollers

### ISSUE THREAD

**Issue by agmartin2** [hackl/TikZ-StructuralAnalysis#5]
Hi, Jürgen,

I have been recently playing with floating bearings using rollers, before noticing about this github repo and that some supports with rollers were already added to it. Thanks for the addition to you and Jose Luis Blanco.

The difference between what I prepared and what was recently contributed to github is that I used only two rollers and that I named the support type as "2oo" to emphasize that this is a type 2 support represented with two rollers. I think that using this kind of naming is way more intuitive than adding a new number for just an alternative representation of the same support. Also, I am way more used to find two rollers instead of three for that kind of support.

I am aware that this may be a matter of taste, so did not prepare a pull request. However, here goes the suggestion, in case you find it reasonable. If so, I can prepare a pull request for it.

Best regards,

**Comment by agmartin2** [comment]
Hi,

I am attaching an example of how the relevant page in stanli manual would look with some of the changes. It includes putting all floating bearings representations together (I think this is really better), original (slider) version, my two rollers version and current \support{7} three rollers implementation (although tagged as 2ooo) for comparison.

[test-2rollers-floating-bearing.pdf](https://github.com/hackl/TikZ-StructuralAnalysis/files/1498844/test-2rollers-floating-bearing.pdf)

I also mailed Jose Luis Blanco separately with my proposed changes. There are some minor differences between the two versions with rollers (I find mine more consistent with the plain 2 original representation, but others may disagree).

In my experimental local branch (not at github) the three rollers version is made consistent with my two rollers version.

If you find it convenient I can push my changes to github and issue a pull request.

**Comment by hackl** [comment]
Thank you, for your effort. It would be great if you could push your changes.

**Comment by agmartin2** [comment]
Changes pushed to `https://github.com/agmartin2/TikZ-StructuralAnalysis`. They include three commits,

-  Add \support{2oo} and \support{2ooo}. Floating bearings like \support{2}, but using rollers.
  The new definitions in stanli.sty. stanli.tex modified to use them. 

- Remove \support{7}, now superceded by \support{2ooo}. 
  Removal of old definitions.

-  Rename \support{8} to \support{4ooo} and merge with \support{4} in stanli manual.

Did not update stanli.pdf in git repo to make merges easier. 

Also, I added a \newpage after \support{2} section in stanli.tex to avoid leaving one definition line behind. This is surely done better in a different way (minipages ...).

I have always worked with plain git repos and this is the first time I use github. Do you want me to issue a pull request for these changes?

By the way, I have been looking about adding an additional representation for springs using coils and a smoother version for the torsion spring using a fake spiral. Will let you know.

Best regards

**Comment by hackl** [comment]
I merged the suggested changes for the supports with rollers

**Comment by agmartin2** [comment]
Thanks for the merging, closing this issue.

Best regards,
